// Shared color palette for the Worker Profile screen
export const ProfileColors = {
  primary: '#000666',
  onPrimary: '#ffffff',
  primaryFixed: '#e0e0ff',
  primaryMuted: 'rgba(0,6,102,0.08)',
  background: '#f7f7fb',
  surface: '#ffffff',
  surfaceContainerLow: '#f6f2f8',
  surfaceContainerLowest: '#ffffff',
  surfaceContainer: '#f0edf2',
  surfaceContainerHigh: '#eae7ed',
  onSurface: '#1b1b1f',
  onSurfaceVariant: '#454652',
  outline: '#767683',
  outlineVariant: '#c6c5d4',
  secondary: '#006b5e',
  secondaryContainer: '#94f0df',
  onSecondaryContainer: '#006f62',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  amber: '#F59E0B',
  amberBg: '#FEF3C7',
  green: '#15803d',
  greenBg: '#dcfce7',
  teal: '#0f766e',
  tealBg: '#ccfbf1',
  purple: '#7c3aed',
  purpleBg: '#ede9fe',
  blue: '#1d4ed8',
  blueBg: '#dbeafe',
} as const;

export type ProfileColor = typeof ProfileColors;
